posts/urls.py
from django.urls import path
from .views import list_view,like_unlike_post, PostDeleteView, PostUpdateView, post_create

app_name = 'posts'

urlpatterns = [
    path('', list_view, name='main-post-view'),
    path('all/', post_create, name='add-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

webweaver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . views import home_view
from posts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    # path('accounts/', include('allauth.urls')),
    # path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout'),
    path('webteam/', web_team, name="web_team"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main/footer.html
<footer>
  <!-- <div class="leftieee">
      © PICT IEEE Student Branch
    </div> -->
  <div class="middleieee">
    &copy; Web Weaver | Made with ❤️ by <a href="{% url 'web_team' %}">PISB Web Team</a>
  </div>
  <!-- <div class="lastieee">
      <div class = "social-links">

        <a href = "#"><i class = "fab fa-linkedin-in"></i></a>
        <a href = "#"><i class = "fab fa-youtube"></i></a>
        <a href = "#"><i class = "fab fa-instagram"></i></a>
  
      </div>
    </div> -->

</footer>

templates/main/home.html
<!doctype html>
<html lang="en">
{% load static %}
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link href={% static 'vivify.min.css' %} rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
  <link rel="stylesheet" href={% static 'home.css' %}>
  <link rel="stylesheet" href={% static 'modal.css' %}>
  <link rel="stylesheet" href={% static 'index.css' %}>
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

  <title>Web Weaver</title>
  <link rel="shortcut icon" type="image/png" href={% static 'pisb-favicon.png' %}>
  <script>
    window.console = window.console || function (t) {};
  </script>
  <script>
    if (document.location.search.match(/type=embed/gi)) {
      window.parent.postMessage("resize", "*");
    }
  </script>
</head>

<body>
  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <a href="{{path_to_home}}" style="color: white; text-decoration: none; font-weight: 700; font-size: 22px;">
          <img src="{% static 'web-weaver.png' %}" alt="Bootstrap" width="65" class="d-inline-block align-top"
            style="position: fixed;">
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
      <a href="{{path_to_home}}">HOME</a>
      <a href="{{path_to_posts}}">POSTS</a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_add_posts}}">ADD POST</a>
      <a href="{% url 'logout' %}" data-toggle="modal" data-target="#exampleModal">{{request.user.username}}</a>
      {% else %}
      <a href="{% url 'login-view' %}">LOGIN</a>
      <a href="https://credenz.in/">REGISTER</a>
      {% endif %}
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          LOGOUT <i class="fa fa-lock"></i><br><br>
          <i class="fa fa-question-circle"></i> Are you sure you want to logout?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <div class="modal-footer"><a class="btn btn-danger btn-block" href={% url 'logout' %}>Logout</a></div>
        </div>
      </div>
    </div>
  </div>
  <!-- <nav class="navbar navbar-expand-lg ">
    <a style="padding:0px" class="navbar-brand" href="{{path_to_home}}"><img src={% static 'web (1).png' %} alt="" height="50px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fas fa-bars"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <li>
          <a class="nav-link active" href="{{path_to_home}}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="vline">
          <a class="nav-link active" href="">|<span class="sr-only"></span></a>
        </li>
        <li>
          <a class="nav-link active" href="{{path_to_posts}}">POSTS <span class="sr-only">(current)</span></a>
        </li>
        <li class="vline">
          <a class="nav-link active" href="">|<span class="sr-only"></span></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{{path_to_add_posts}}">ADD POST <span class="sr-only">(current)</span></a>
        </li>
        <li class="vline">
          <a class="nav-link active" href="">|<span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">{{request.user}}<span class="sr-only">(current)</span></a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="https://credenz.in/">REGISTER<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        </li>

      </ul>

    </div>
  </nav> -->

  <div class="webweaver">

    <div class="headingname driveInTop">
      <p class="titlename">WEB WEAVER</p>
      <p>Bring out the developer in you with Web Weaver 22 ! <br>
        Show case your skills as a web developer with this website creating contest .
        <br>
        Be a creative genius, build an aesthetic site on the given theme. </p>
      <div class="links ">
        <button type="button" class="glow-on-hover" data-toggle="modal"
          data-target="#introduction">INTRODUCTION</button>
        <button type="button" class="glow-on-hover" data-toggle="modal"
          data-target="#instructions">INSTRUCTIONS</button>

        <!-- Modal -->
        <div class="modal fade" id="introduction" tabindex="-1" role="dialog" aria-labelledby="introduction"
          aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h2 class="modal-title" id="exampleModalCenterTitle">Introduction</h2>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
              </div>
              <div class="modal-body">
                Bored of monotonous college assignments ?
                <br>
                Bring out the developer in you with Web Weaver 22 !
                <br><br>

                Web weaver is a web development event where the participants can participate individually or in a group
                of 2
                and
                are required to submit websites on the given theme .Sites submitted on the first day are shortlisted and
                promoted for round 2 with specific changes to be applied.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="instructions" tabindex="-1" role="dialog" aria-labelledby="instructions"
          aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h2 class="modal-title" id="exampleModalCenterTitle">Instructions</h2>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
              </div>
              <div class="modal-body">
                <ul>
                  <li>
                    <span>1.</span> Register Yourself for Web Weaver contest organised by PISB.
                  </li>
                  <li>
                    <span>2.</span> Create a post to showup your website
                  </li>
                  <li>
                    <span>3.</span> You have to upload Screen Shot of your website.
                  </li>
                  <li>
                    <span>4.</span> In the information section of website, Name , Title, Link for your website<br> and a
                    short description about your website you have to submit.
                  </li>
                  <li>
                    <span>5.</span> Viewers visits your website through the post that you have uploaded.
                  </li>
                </ul>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="svgs">
      <img class="cssanimation hu__hu__" src={% static 'Website Creator-amico.svg' %} alt="">
    </div>

  </div>


  <!-- footer -->
  <footer>
    <!-- <div class="leftieee">
      © PICT IEEE Student Branch
    </div> -->
    <div class="middleieee">
      Web Weaver | Made with ❤️ by <a href="{% url 'web_team' %}" style="color: #2691D9;">PISB Web Team</a>
    </div>
    <!-- <div class="lastieee">
      <div class="social-links">

        <a href="https://www.linkedin.com/company/pisbieee"><i class="fab fa-linkedin-in"></i></a>
        <a href="https://www.youtube.com/c/PICTIEEEStudentBranch"><i class="fab fa-youtube"></i></a>
        <a href="https://instagram.com/pictieee?utm_medium=copy_link"><i class="fab fa-instagram"></i></a>

      </div>
    </div> -->

  </footer>
  <!-- end of footer -->


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    $(document).ready(function () {
      $("a").on('click', function (event) {

        if (this.hash !== "") {
          event.preventDefault();

          var hash = this.hash;

          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 800, function () {

            window.location.hash = hash;
          });
        }
      });
    });
  </script>
  <script src='https://codepen.io/juliangarnier/pen/75efae7724dbc3c055e918057fc4aca5.js'></script>

  <script
    src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-1b93190375e9ccc259df3a57c1abc0e64599724ae30d7ea4c6877eb615f89387.js">
  </script>

  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script id="rendered-js">
    AOS.init({
      offset: 400, // offset (in px) from the original trigger point
      delay: 0, // values from 0 to 3000, with step 50ms
      duration: 1000 // values from 0 to 3000, with step 50ms
    });
    //# sourceURL=pen.js
  </script>

</body>

</html>

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}

<nav class="navbar navbar-expand-lg ">
    <a class="navbar-brand" href="index.html">WEB WEAVER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fas fa-bars"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <li>
          <a class="nav-link active" href="{{path_to_home}}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="vline">
          <a class="nav-link active" href="">|<span class="sr-only"></span></a>
        </li>
        <li>
          <a class="nav-link active" href="{{path_to_posts}}">POSTS <span class="sr-only">(current)</span></a>
        </li>
        <li class="vline">
          <a class="nav-link active" href="">|<span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{path_to_add_posts}}">ADD POSTS <span class="sr-only">(current)</span></a>
        </li>
        </li>

      </ul>

    </div>
  </nav>